# CFLAGS = -I../Include -I/usr/include -c
CC=cc
all :	time_span_out.o \
	output_simple.o \
	output_data.o \
	output_sac.o \
	output_ah.o \
	ah_resp.o \
	output_resp.o \
	output_css.o \
	output_mini.o \
	output_seed.o \
	output_LOG.o \
	steim.o\
	rdseed.o \
	alt_response.o\
	output_event_info.o \
	summary.o \
	output_segy.o\
	output_b2k.o \
	output_stn_chn_comments.o\
	atc.o
