CC=cc
all : alloc_linklist_element.o \
allocation_error.o \
cmdlineproc.o \
find_wordorder.o \
memncpy.o \
parse_double.o \
parse_int.o \
parse_long.o \
parse_nchar.o \
parse_varlstr.o \
read_blockette.o \
read_logical_record.o \
split.o \
swap_2byte.o \
swap_4byte.o \
timeadd.o \
timeadd_double.o \
timeaddphase.o \
timedif.o \
timecvt.o \
timeprt.o \
timecmp.o \
timetol.o \
timeqc.o \
timepch.o \
log_errors.o \
strlst.o\
get_date.o \
delaz.o
