CC=cc
all : convert_seedhdr.o \
decode_echery.o \
decode_graef.o \
decode_rstn.o \
decode_32bit.o \
decode_16bit.o \
decode_ieeefloat.o \
decode_ieeedouble.o \
decode_asro.o \
decode_cdsn.o \
decode_dwwssn.o \
decode_sro.o \
decode_steim.o \
decode_geoscope.o \
decode_ddl.o \
decode_usnsn.o \
decode_steim2.o \
init_data_hdr.o \
process_time_span.o \
process_event_requests.o \
process_data.o 
